id_list = []  # list of autogenerated, unique ID's

def autoGen():
    import random
    gen = random.randint(0,10000000)
    if gen not in id_list:
        id_list.append(gen)
        return gen

def create_bookstore(name):
    bookstore = {}
    bookstore['name'] = name
    bookstore['books'] = []
    bookstore['authors'] = []
    return bookstore

def add_author(bookstore, name, nationality):
    author = {}
    author['name'] = name
    author['nationality'] = nationality
    uniqueID = autoGen()
    author['id'] =  uniqueID
    bookstore['authors'].append(author)
    return author

def add_book(bookstore, title, isbn, author_id):
    book = {}
    book['title'] = title
    book['isbn'] = isbn
    book['author_id'] = author_id
    uniqueID = autoGen()
    book['id'] = uniqueID
    bookstore['books'].append(book)
    return book

def get_author_by_id(bookstore, author_id):
    for x in bookstore['authors']:
        if x['id'] == author_id:
            return x

def get_book_by_id(bookstore, book_id):
    for x in bookstore['books']:
        if x['id'] == book_id:
            return x

def get_author_by_name(bookstore, name):
    list = bookstore['authors']
    for x in list:
        if x['name'] == name:
            return x
    
    
def get_book_by_title(bookstore, title):
    list = bookstore['books']
    for x in list:
        if x['title'] == title:
            return x

def get_books_by_author(bookstore, author_id):
    set_of_books = []
    list = bookstore['books']
    for x in list:
        if x['author_id'] == author_id:
            set_of_books.append(x)
    return set_of_books
